name: Run main.py Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-main-py:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Run main.py
      run: python main.py
